name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'              # Speed up installs using Node/NPM cache

      - name: Install dependencies
        run: npm ci

      # If allure packages aren't in your lockfile yet, uncomment these 2 lines:
      # - name: Ensure Allure deps (one-time; prefer adding to package.json)
      #   run: npm i -D allure-playwright allure-commandline

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests (sharded) with reporters
        # We run blob + allure reporters together.
        # - blob reporter feeds the merge step if you also want to use it later
        # - allure-playwright outputs "allure-results" per shard
        run: |
          npx playwright test \
            --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }} \
            --reporter=line,blob,allure-playwright

      - name: Upload blob report (per shard)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: blob-report-${{ matrix.shardIndex }}
          path: blob-report
          retention-days: 1

      - name: Upload Allure results (per shard)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.shardIndex }}
          path: allure-results
          retention-days: 3

  merge-reports:
    # Merge even if some shards failed, but still skip on cancellation
    if: ${{ always() && !cancelled() }}
    needs: [playwright-tests]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # If allure packages aren't in your lockfile yet, uncomment these 2 lines:
      # - name: Ensure Allure deps (one-time; prefer adding to package.json)
      #   run: npm i -D allure-playwright allure-commandline

      - name: Download Allure results from all shards
        uses: actions/download-artifact@v4
        with:
          path: merged-allure-results
          pattern: allure-results-*
          merge-multiple: true   # Flattens all allure-results-* into this folder

      # Optional: If you also want to keep using Playwright's merged blob (not required for Allure),
      # uncomment this block to produce a single merged blob or an extra HTML report.
      # - name: Download blob reports (optional)
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: all-blob-reports
      #     pattern: blob-report-*
      #     merge-multiple: true
      #
      # - name: (Optional) Merge blob reports into Playwright HTML
      #   run: npx playwright merge-reports --reporter html ./all-blob-reports
      #
      # - name: (Optional) Upload Playwright HTML (in addition to Allure)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: playwright-html--attempt-${{ github.run_attempt }}
      #     path: playwright-report
      #     retention-days: 7

      - name: Generate Allure HTML report
        # Generates ./allure-report from merged-allure-results
        run: npx allure-commandline generate ./merged-allure-results --clean -o ./allure-report

      - name: Upload Allure HTML report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report--attempt-${{ github.run_attempt }}
          path: allure-report
          retention-days: 14
